const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    
    definitions: {
        Brand: {
            $brand: "NewBrand",
        },
        Cart: {
            $ProductId: 3,
            $quantity: 10
        },
        Category: {
            $name: "NewCategory",
        },
        User: {
            $credentials: "johnnyDoe@gmail.com",
            $password: "P4ssword"
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})
